stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login 192.168.1.78:32500 -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t 192.168.1.78:32500/mern-demo .
    - docker push 192.168.1.78:32500/mern-demo

deploy:
  stage: deploy
  script:
    - microk8s kubectl apply -f /home/sst_admin/Source/mern-demo/deploy-mern-demo.yaml