stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: sonar-scanner -Dsonar.projectKey=sonar-test -Dsonar.sources=. -Dsonar.host.url=http://192.168.1.78:31264 -Dsonar.login=d2d7f8a40d52c9ad9cdd16b7b415002f61860379 -Dsonar.qualitygate.wait=true

build:
  stage: build
  script:
    - docker login 192.168.1.78:31779 -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker pull 192.168.1.78:31779/sprint4-demo:latest || true
    - docker build --cache-from 192.168.1.78:31779/sprint4-demo:latest --tag 192.168.1.78:31779/sprint4-demo:$CI_COMMIT_SHA --tag 192.168.1.78:31779/sprint4-demo:latest .
    - docker push 192.168.1.78:31779/sprint4-demo:$CI_COMMIT_SHA
    - docker push 192.168.1.78:31779/sprint4-demo:latest

deploy:
  stage: deploy
  script:
    - docker login 192.168.1.78:31779 -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - microk8s kubectl delete deployments sprint4-demo
    - microk8s kubectl apply -f deploy-sprint4-demo.yaml