image: docker:19.03.12
services:
  - name: docker:19.03.12-dind
    command: ["--insecure-registry=192.168.1.78:31779"]

variables: 
  DOCKER_TLS_CERTDIR: ''

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login 192.168.1.78:31779 -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker pull 192.168.1.78:31779/sprint4-demo:latest || true
    - docker build --cache-from 192.168.1.78:31779/sprint4-demo:latest --tag 192.168.1.78:31779/sprint4-demo:$CI_COMMIT_SHA --tag 192.168.1.78:31779/sprint4-demo:latest --build-arg NPM_TOKEN=${NPM_TOKEN} .
    - docker push 192.168.1.78:31779/sprint4-demo:$CI_COMMIT_SHA
    - docker push 192.168.1.78:31779/sprint4-demo:latest

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
     - kubectl config set-cluster sst-microk8s --server="${SERVER}"
     - kubectl config set clusters.microk8s-cluster.certificate-authority-data ${CAD}
     - kubectl config set-credentials sst-microk8s --token="${TOKEN}"
     - kubectl config set-context microk8s --cluster=sst-microk8s --user=sst-microk8s
     - kubectl config use-context sst-microk8s
     - kubectl config current-context
     - kubectl config view
     - kubectl get all --all-namespaces

    