stages:
  - test
 
test:
  stage: test
  script: sonar-scanner -Dsonar.projectKey=sonar-test -Dsonar.sources=. -Dsonar.host.url=http://192.168.1.78:31264 -Dsonar.login=d2d7f8a40d52c9ad9cdd16b7b415002f61860379 -Dsonar.qualitygate.wait=true