stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t jtp03a/mern-demo .
    - docker push jtp03a/mern-demo

deploy:
  stage: deploy
  script:
    - microk8s kubectl create deployment mern-demo --image=jtp03a/mern-demo:latest