apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-demo
  labels:
    app: mern-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-demo
  template:
    metadata:
      labels:
        app: mern-demo
    spec:
      containers:
      - name: mern-demo
        image: jtp03a/mern-demo:latest
        env:
        - name: REACT_APP_DB_CONN
          value: "$(REACT_APP_DB_CONN)"
        ports:
        - containerPort: 4000