apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint4-demo2
  labels:
    app: sprint4-demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprint4-demo2
  template:
    metadata:
      labels:
        app: sprint4-demo2
    spec:
      containers:
      - name: sprint4-demo2
        image: 192.168.1.78:31779/sprint4-demo:latest
        env:
        - name: DB_CONN
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: mongodb_conn
        - name: NPM_TOKEN
          valueFrom:
            secretKeyRef:
              name: npmreg-secrets
              key: npm-token        
        ports:
        - containerPort: 4000